<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationInsightsResourceId>/subscriptions/4258bb97-25ca-4b30-bdeb-bb17a6d43f91/resourcegroups/lab1ResourceGroup/providers/microsoft.insights/components/lab1</ApplicationInsightsResourceId>
    <UserSecretsId>502174d4-4290-4699-b912-8315e4d800fd</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.13.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.22.0" />
  </ItemGroup>

</Project>
